### ISSUE TITLE
Add optional Serde support

### ISSUE THREAD

**Issue by dtolnay** [orium/rpds#1]
In #rust today someone was struggling to serialize rpds::Vector ([logs](https://botbot.me/mozilla/rust/2017-12-29/?msg=95160027&page=10)). It would be great to have Serde impls for these data structures that can be enabled by a `serde` cfg.

**Comment by orium** [comment]
In the next few days I will probably not be able to get any coding done, but once I'm I will work on it.  (Meanwhile if someone wants to work on a PR I might be able to review/merge it.)

**Comment by idupree** [comment]
I started implementing this in https://github.com/idupree/rpds/commits/serde-impls -- does it look reasonable so far?

**Comment by dtolnay** [comment]
Looks good so far!

**Comment by orium** [comment]
Yup, looks good.  I only have some cosmetic/organization suggestions but I will leave that to the PR.

**Comment by idupree** [comment]
Might I have your cosmetic suggestions now so that I don't have to redo cosmetic changes for every data structure?

**Comment by idupree** [comment]
(I could send it in a provisional pull request if it's easier to comment on that way)

**Comment by idupree** [comment]
I've done Vector/List/Queue/Stack so far. Is it intentional that Stack lacks a len() method, or should I add one in a separate pull request?

**Comment by idupree** [comment]
Implemented all of them (Vector, List, Queue, Stack, RedBlackTreeSet, HashTrieSet, RedBlackTrieMap, HashTrieMap) https://github.com/orium/rpds/pull/2

**Comment by idupree** [comment]
Implemented all of them (Vector, List, Queue, Stack, RedBlackTreeSet, HashTrieSet, RedBlackTrieMap, HashTrieMap). Note in case you had pulled the initial commit series: I've git-rebased since then. https://github.com/orium/rpds/pull/2

**Comment by orium** [comment]
Closed by #4
