### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by noahdesu** [orium/rpds#12]
I have been hacking on a persistent red-black tree in C++ recently. I just wanted to say thank you for your Rust implementation. It's been incredibly useful in getting this working!

**Comment by orium** [comment]
I'm happy to hear that!  If you find a nicer way to rebalence on `remove()` let me know :)

**Comment by noahdesu** [comment]
@orium ditto. all i've heard is that delete is messy, and there's no way around it. we are currently using a different persistent red-black tree algorithm, and it is also complicated, but it does seem to be a bit less complex / less code: https://github.com/cruzdb/cruzdb/blob/master/src/db/persistent_tree.h#L180
