### ISSUE TITLE
`RedBlackTreeSet`'s docs mention non-existent `get` operation

### ISSUE THREAD

**Issue by phrohdoh** [orium/rpds#63]
https://github.com/orium/rpds/blob/ed9e65eac71226c60d9f2842a48436f9fa1b70e5/src/set/red_black_tree_set/mod.rs#L81-L92

```
error[E0599]: no method named `get` found for struct `RedBlackTreeSet` in the current scope
   --> src/lib.rs:456:17
    |
456 |             set.get(x)
    |                 ^^^ method not found in `RedBlackTreeSet<Val>`
```

---

For my use-case it'd be useful to have a `get` that returned the given key, as if the set were a map where the keys are also the values, (or `None`, _some_ value indicating lack of value in the set).

I _can_ wrap the set type(s) with a custom implementation to achieve the above, but worry about losing the traits/impls that the set type(s) already have (or having to forward, with whatever pain may come).

**Comment by orium** [comment]
Implemented.  Will cut a release now.

**Comment by phrohdoh** [comment]
Thank you!
