### ISSUE TITLE
Serializing multiple instances efficiently 

### ISSUE THREAD

**Issue by jgarvin** [orium/rpds#71]
If I have a PDS, and I do many operations in it and keep some of the intermediate states, is there a way to serialize them to disk that retains the sharing? E.g. if I have a massive table with a million keys and I insert one extra element and then I want to serialize both the pre-insert and post-insert versions, is there a way to do so where I don't end up with 2 million keys on disk? I'm assuming that's what happens if I just throw each into serde separately.

**Comment by orium** [comment]
No, there's currently no way to serialize multiple instances of the data structures with sharing.  I don't think rpds will support something like that.  I would consider keeping a "operations log" for something like that.
