### ISSUE TITLE
Add a "feature" to remove _mut methods

### ISSUE THREAD

**Issue by will-lx** [orium/rpds#73]
This is a feature request/offer to contribute. 

As a framework maintainer at my company, I'd love to be able to prevent my users from calling any `_mut` methods on rpds `structures`. I wonder if having a feature to hide these methods from public visibility (or from compilation) is of interest to other folks? If so, I'd be happy to take a swing at implementing this. Thanks!

**Comment by orium** [comment]
Hi.  Can you elaborate on why that's desirable?  If a user has ownership of a data structure they can achieve the same thing as one of the `_mut()` methods.

**Comment by will-lx** [comment]
Assuming the inner attributes of the data structure are not declared `pub`, the callee receiving access to the red black tree, for example, could be restricted from mutating anything. This would ensure that using these structures could be made entirely immutable, which is useful for certain STM atomic block scenarios I'm playing with.

**Comment by will-lx** [comment]
Hey, I believe I have found an alternative approach here to avoid the situation I was talking about. Essentially, I can cloak access to the persistent data structures behind a "ConstRef" which will prevent a callsite from accidentally calling methods such as "insert_mut", "remove_mut", etc... since those require `&mut` access. I'm not sure if there's an alternative structure in the `std` library, but for what it's worth, here's the structure I'm wrapping around my rpds structures:

```
use std::fmt;

pub struct ConstRef<T>(T);

impl<T> From<T> for ConstRef<T> {
    fn from(t: T) -> Self {
        Self(t)
    }
}

impl<T> std::ops::Deref for ConstRef<T> {
    type Target = T;
    fn deref(&self) -> &T {
        &self.0
    }
}
```

**Comment by will-lx** [comment]
I should add that after working with the `rpds` crate for a bit I realized that I didn't really want to drop support for the `*_mut` methods, since they come in super handy. I just wanted to prevent certain codepaths from accessing them for their own sake.
