### ISSUE TITLE
FYI: Python bindings / Minor README question

### ISSUE THREAD

**Issue by Julian** [orium/rpds#83]
Hi there! Thanks for writing rpds.

FYI, a few months back I wrote bindings to it from Python*. They live [here](https://github.com/crate-py/rpds/).

The primary reason was in order to use rpds in my [Python JSON Schema implementation](https://github.com/python-jsonschema/jsonschema), so perhaps it's nice to know that that immediately shot `rpds` up into one of the top 100 used Python packages :)

<img width="705" alt="Screenshot 2023-09-13 at 09 27 13" src="https://github.com/orium/rpds/assets/329822/e3ba4ffb-0c17-40b8-bdde-e9b12af19f17">

(that's monthly number of downloads, shown from [here](https://hugovk.github.io/top-pypi-packages/))

* Importantly, the amount of rpds that I wrote bindings for is literally the minimal amount needed for my use case. I intend to at some point come back and bind the entire public API, unless hopefully someone comes along to help sooner by sending PRs.

I suppose a minor README question is whether you'd care for a PR mentioning the existence of the Python bindings. Happy to send one if so.

(Obviously feel free to close this either way!)

Thanks again for the library!

**Comment by orium** [comment]
Hi @Julian.  Thanks for making rpds-py, I just learned about it recently (through #81).

Yes, I'm happy to include a mention to rpds-py in the README.  Can you add a section about bindings in the bottom of the README?  Make sure to have a link to the rpds-py github repo.

**Comment by Julian** [comment]
Great! Glad to hear it! Sent as #84, thanks again!
