### ISSUE TITLE
Is `clone()` O(1) ?

### ISSUE THREAD

**Issue by lie-yan** [orium/rpds#97]
https://github.com/orium/rpds/blob/abc1c648568a45e5c4c0f96bce7c1d9dc2dc3011/src/map/red_black_tree_map/mod.rs#L96

https://github.com/orium/rpds/blob/abc1c648568a45e5c4c0f96bce7c1d9dc2dc3011/src/map/red_black_tree_map/mod.rs#L139-L146

It seems that `Node.clone()` is doing recursive copy. Is it really O(1) in time?

**Comment by orium** [comment]
left and right are `SharedPointer`, which is either an `Arc` or an `Rc`, so cloning them does not clone the entire subtree, just creates a new smart pointer that bumps the ref count.

**Comment by lie-yan** [comment]
I see. Thanks.
